### ISSUE TITLE
'OIC Physicians' on Head

### ISSUE THREAD

**Issue by jaskim123** [LuskinOIC/website#293]
![image](https://github.com/LuskinOIC/website/assets/148907402/5188d4bc-e870-42e0-afcf-963d880df873)

For this item, we would want to change the title at the top left so it correctly states LuskinOIC Physicians, rather than OIC Physicians.

For the next item, it was difficult for me to start creating a bio for researchers:
![image](https://github.com/LuskinOIC/website/assets/148907402/0b1b4a4a-b717-4552-b854-53dbef254fa3)

I had to use the 'physicians bio' rather than 'members bio', as looking at my example on staging shows no text being shown other than the title. (The divider and overview was not showing up, for example. Shown here):
![image](https://github.com/LuskinOIC/website/assets/148907402/2b3b579a-17fb-4ae2-8724-97a2bef5ac26)

We would need to ensure (once we start putting in bios for non-physicians) that the slug can say 'researchers' , along with 'physical therapist', 'occupational therapist', 'nurse practitioner', 'physician assistant', etc.

**Comment by YolineB** [comment]
Thanks for the information @jaskim123 

For clarification, you want:

1) The tab to change from OIC Physicians to LuskinOIC Physicians

2) We want the url to reflect the person's position, choices being: 'researchers' , along with 'physical therapist', 'occupational therapist', 'nurse practitioner', 'physician assistant'. Does this mean we need a 'researchers' section in the main providers index page?

3) Regarding the individual bio page section display, the member bio was set up with the understanding that it would just be a small two column layout. Looks like researchers will have more information, so I can adjust members or add another provider. 

I will create two different changes to ge the LuskinOIC physicians donoe.

**Comment by jaskim123** [comment]
Hi @YolineB ,
For clarification:
1: Yes, this would also be the first priority in relation to the other 2 tasks. On top of this, I also notice on the home page it says 'pediatric orthopedic doctor' rather than 'pediatric orthopaedic doctor'; is this something I can change on my own in Contentful?
2. For adding a researchers section, Eunha and I will give a definitive answer later today, as labeling them 'providers' might be a bit confusing. For now, let's not.
3. For the bio section on researchers, would the best course of action be to maybe create a 'providers' bio page section in Contentful? I'm saying this as I'm under the assumption the slugs 'physcians' is interlocked with 'physician bio' in Contentful. Let me know if im mistaken, or if i may need to add further clarification.

**Comment by YolineB** [comment]
@jaskim123 

1) I can update the homepage tab, currently made a change so that you can edit the SEO Meta Tag fields for it. It will take a couple of minutes to complete the build but you can now edit it in Page Type > Landing > SEO Meta Tag component

2) That makes sense - I can add another type to 'members' and then make adjustments so that we can add more page sections to their bio pages, as we are doing with the providers. 

3) Implementing the member type 'Researcher' will allow us to remove the providers from the researchers/leadership members

On that note, it looks like later down the line, we can look into combining all types people and having a drop down of type. This will in turn clean up our component types too. Once we get our bigger issue tickets we can look into re organizing the people now that we are getting a firmer understanding of the different fields.
